name: Update README ⭐

on: [push]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 2398405
          leaderboardId: 1782552
          sessionCookie: ${{ secrets.AOC_SESSION }}
          headerPrefix: "##"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars
